### ISSUE TITLE
编译到最后找不nanopi-r5s-rk3568-idbloader.img，求助

### ISSUE THREAD

**Issue by fishg** [DHDAXCW/lede-rk3568#3]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
Creating filesystem with parameters:
    Size: 33554432
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 2048
    Inode size: 256
    Journal blocks: 0
    Label: kernel
    Blocks: 8192
    Block groups: 1
    Reserved blocks: 0
    Reserved block group size: 7
Created filesystem with 14/2048 inodes and 4404/8192 blocks
+ dd if=/mnt/sdc2/project/git/r5s-lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/tmp/openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-squashfs-sysupgrade.img.gz.kernel of=/mnt/sdc2/project/git/r5s-lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/tmp/openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-squashfs-sysupgrade.img.gz bs=512 seek=65536 conv=notrunc
65536+0 records in
65536+0 records out
33554432 bytes (34 MB, 32 MiB) copied, 0.172639 s, 194 MB/s
+ rm -f /mnt/sdc2/project/git/r5s-lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/tmp/openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-squashfs-sysupgrade.img.gz.kernel
# Copy the idbloader and the u-boot image to the image at sector 0x40 and 0x4000
dd if="/mnt/sdc2/project/git/r5s-lede/staging_dir/target-aarch64_generic_musl/image"/nanopi-r5s-rk3568-idbloader.img of="/mnt/sdc2/project/git/r5s-lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/tmp/openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-squashfs-sysupgrade.img.gz" seek=64 conv=notrunc
dd: failed to open '/mnt/sdc2/project/git/r5s-lede/staging_dir/target-aarch64_generic_musl/image/nanopi-r5s-rk3568-idbloader.img': No such file or directory
make[5]: *** [Makefile:80: /mnt/sdc2/project/git/r5s-lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/tmp/openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-squashfs-sysupgrade.img.gz] Error 1
make[5]: Leaving directory '/mnt/sdc2/project/git/r5s-lede/target/linux/rockchip/image'
make[4]: *** [Makefile:24: install] Error 2
make[4]: Leaving directory '/mnt/sdc2/project/git/r5s-lede/target/linux/rockchip'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/mnt/sdc2/project/git/r5s-lede/target/linux'
time: target/linux/install#241.80#42.46#190.37
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/install] Error 1
make[2]: Leaving directory '/mnt/sdc2/project/git/r5s-lede'
make[1]: *** [target/Makefile:19: /mnt/sdc2/project/git/r5s-lede/staging_dir/target-aarch64_generic_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/mnt/sdc2/project/git/r5s-lede'
make: *** [/mnt/sdc2/project/git/r5s-lede/include/toplevel.mk:230: world] Error 2

**Comment by DHDAXCW** [comment]
我大意了

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/lede-rk3568/commit/8e9f12fabb145ae028009ccb11c5de1a6a03e260
