### ISSUE TITLE
生成的r5s包属于线刷还是卡刷包呢？

### ISSUE THREAD

**Issue by fishg** [DHDAXCW/lede-rk3568#5]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
成功生成了镜像：
openwrt-rockchip-armv8-friendlyelec_nanopi-r5s-squashfs-sysupgrade.img.gz

但不知道是属于卡刷还是线刷？以及能指定生成卡刷和线刷包吗

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/DoorNet2/blob/main/emmc.md
